### PR TITLE
Add information about C++ / Qt interface

### PR DESCRIPTION
**Pull request by Shatur95**
I really like your program, thank you for your awesome work!
But I think it lacks interface. I decided to fix it :) Just [check it out](https://github.com/Shatur95/optimus-manager-qt).

I also suggest:
1. Use `1 / 0` instead of `yes / no` for easier parsing with [QSettings](https://doc.qt.io/qt-5/qsettings.html) (it can be done automatically);
2. If you agree with the first suggestion, then for consistency it would be better to replace for the options `yes / no / <empty>` for `tearfree` with `enable / disable / <empty>`;
3. Move the Python-tray to a separate package to allow users choose which interface to use;
4. Add bbswitch to optional dependencies in your package, as it can be used.

Thanks!

### CODE REVIEW

**Comment by Askannz** [comment]
That Qt interface looks nice ! But I cannot get it to work : I tried installing it from https://aur.archlinux.org/packages/optimus-manager-qt/, but running `optimus-manager-qt` does not work : the GUI and the systray is never created, nothing is printed in the console, it just hangs until I kill it.

Any step I've missed ?

**Comment by ShaturIQ** [comment]
No, it must just works... What desktop environment do you use?

**Comment by Askannz** [comment]
KDE on Archlinux, everything up-to-date I believe.

**Comment by ShaturIQ** [comment]
At startup, the icon should just appear in the system tray, maybe it is in the "hidden icons"?
Also do you replace KDE=false to KDE=true  in PKGBUILD? This is not necessary, but improves KDE integration.

**Comment by Shatur95** [comment]
At startup, the icon should just appear in the system tray, maybe it is in the "hidden icons"?
Also do you replace KDE=false with KDE=true in PKGBUILD? This is not necessary, but improves KDE integration.

**Comment by Shatur95** [comment]
I fixed the problem! I use the Papirus icon theme in which there are `prime-intel` and `prime-nvidia` icons, and you most likely have the Breeze icon theme, where they don't exist. Because of this, a transparent icon is displayed in the system tray. I have already fixed it. As soon as the new version of Optimus Manager is released, I will also release an update of Optimus Manager Qt (since now I have implemented the features that are present only in your git-version, such us [this](https://github.com/Askannz/optimus-manager/commit/2d878c517017f6f76af477cb693dc56adc49164b)).

**Comment by Askannz** [comment]
Ah yes, I probably missed the transparent icon, sorry.
It's working now, but the icons are still missing, because of that problem you mentioned. Couldn't you bundle the icons inside the app, just like I did with the current tray application ? I grabbed the icons from https://github.com/alecive/FlatWoken.

**Comment by Shatur95** [comment]
I have already fixed this problem in the master branch. Now if there is no selected icon, the xorg icon will be used.
Unfortunately, there is no possibility to bundle icons with the application, since in the settings, an icon is selected from a file or from a theme. But the user will be able to choose the icon himself, which, by style, fits to the design of his system :)

**Comment by Askannz** [comment]
I did some testing, and you can just have your application install icons to `/usr/share/icons/hicolor/`. 
The icons in this folder are only used if nothing is provided by the current theme. That way, it would not override the Papirus icons in your case, and we would still have default icons to show the user if their theme does not provide any.

For instance, if you have a SVG icon `prime-intel.svg`, you need to put it in `/usr/share/icons/hicolor/scalable/status/`. If it's a PNG `prime-intel.png` with a fixed size (say, 256x256), you need to put it in `/usr/share/icons/hicolor/256x256/status`.

**Comment by ShaturIQ** [comment]
Hmm, good idea!
I will implement it :)

**Comment by Shatur95** [comment]
Hmm, good idea!
I will implement it :)

**Comment by Shatur95** [comment]
Done!

How about my suggestions from the first post?
I would also suggest adding the ability to send settings to the optimus manager daemon. This would allow to change the settings without root rights.

**Comment by Askannz** [comment]
Thanks !

About the other suggestions :

> 1. Use `1 / 0` instead of `yes / no` for easier parsing with [QSettings](https://doc.qt.io/qt-5/qsettings.html) (it can be done automatically);

If I had known people were working on Qt apps I probably would have done that, but I think it's too late now. Changing the format now would break people's configurations, and if I leave the old format as a legacy option you would still have to support it anyways.

> 3. Move the Python-tray to a separate package to allow users choose which interface to use;

Your app is better than the current built-in tray app, so I'll eventually remove that one (so that we can get rid of the PyQt dependency). However I don't want to break people's setup, so I'll leave it for now and add a warning message telling users it's deprecated and they should switch to the new app.

> 4. Add bbswitch to optional dependencies in your package, as it can be used.

Yup, good idea.

> I would also suggest adding the ability to send settings to the optimus manager daemon. This would allow to change the settings without root rights.

I'm not fond of this idea. optimus-manager hooks into systemd, I consider it part of the user's system, so it makes sense that its config is protected by root ownership. Plus, I want to keep the daemon as simple as possible, and that feature would add a whole new level of complexity to it for minimal gain.

**Comment by Shatur95** [comment]
Okay, I think you're absolutely right :)

**Comment by Askannz** [comment]
Just released v0.8.

**Comment by Shatur95** [comment]
Awesome! I will release the qt-interface today after work.

**Comment by Shatur95** [comment]
Done!

**Pull request merged**
