### PR TITLE
Try a few times before giving up

### LINKED ISSUE #277: Start Intel (OK); Switch NVIDIA (OK); Switch Intel (OK); no more switching: modprobe: FATAL: Module nvidia is in use.
**Describe the bug**
Thanks for this project! I'm switching from bumblebee.

I can switch from Intel to NVIDIA and back to Intel once more, but the `nvidia` module doesn't get unloaded, and `optimus-manager` won't do anything more, complaining that the Xorg pre-start hook failed (logs below).

**System info**
- Arch Linux
- KDE Plasma
- SDDM
- optimus-manager 1.3
- `/etc/optimus-manager/optimus-manager.conf` (I think this is still as default):

```ini
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=
[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking
[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
startup_mode=intel
switching=none
```

**Logs**

```console
$ optimus-manager --status
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20200621T142717.log

Cannot execute command because of previous errors.
```

Best of `/var/log/optimus-manager/switch/switch-20200621T142717.log`:

```
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia']' returned non-zero exit status 1.
optimus_manager.bash.BashError: Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.
```

<details><summary>Full log</summary>

<p>

```
[10] INFO: # Xorg pre-start hook
[10] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'intel', 'current_mode': 'nvidia'}
[10] INFO: Requested mode is: intel
[10] INFO: Checking for GDM display servers
[890] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[890] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[916] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 196, in _unload_modules
    exec_bash("modprobe -r " + " ".join(modules_to_unload))
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 45, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 24, in setup_kernel_state
    _nvidia_down(config)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 65, in _nvidia_down
    _unload_nvidia_modules(available_modules)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 148, in _unload_nvidia_modules
    _unload_modules(available_modules, ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia"])
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 198, in _unload_modules
    raise KernelSetupError("Cannot unload modules %s : %s" % (str(modules_to_unload), str(e)))
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.

[917] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[918] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200621T142717', 'requested_mode': 'intel'}
```

</p>

</details>

In this second Intel session:

```console
$ lsmod | grep -i nvid
nvidia              20520960  0
ipmi_msghandler        77824  2 ipmi_devintf,nvidia
$ sudo modprobe -r nvidia
$ lsmod | grep -i nvid
$ pacman -Qqs nvidia
egl-wayland
lib32-libvdpau
lib32-nvidia-utils
lib32-opencl-nvidia
libvdpau
nvidia-dkms
nvidia-utils
opencl-nvidia
```

**SDDM Configs**

`/etc/sddm.conf.d/20-optimus-manager.conf`:
```ini
[X11]
DisplayCommand=/sbin/prime-offload
DisplayStopCommand=/sbin/prime-switch
```

`/etc/sddm.conf.d/kde_settings.conf`:
```ini
[Autologin]
Relogin=false
Session=
User=andy

[General]
HaltCommand=/usr/bin/systemctl poweroff
Numlock=on
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=breeze
CursorTheme=breeze_cursors

[Users]
MaximumUid=60000
MinimumUid=1000

[X11]
ServerArguments=-dpi 0
```

`/etc/sddm.conf`:
```ini
[General]
InputMethod=

[Theme]
DisableAvatarsThreshold=7
EnableAvatars=true
FacesDir=/usr/share/sddm/faces
ThemeDir=/usr/share/sddm/themes

[Users]
DefaultPath=/bin:/usr/bin:/usr/local/bin
HideShells=
HideUsers=
RememberLastSession=true
RememberLastUser=true
ReuseSession=false

[Wayland]
EnableHiDPI=false
SessionCommand=/usr/share/sddm/scripts/wayland-session
SessionDir=/usr/share/wayland-sessions
SessionLogFile=.local/share/sddm/wayland-session.log

[X11]
# DisplayCommand=/usr/share/sddm/scripts/Xsetup
# DisplayStopCommand=/usr/share/sddm/scripts/Xstop
EnableHiDPI=false
MinimumVT=1
ServerPath=/usr/bin/X
SessionCommand=/usr/share/sddm/scripts/Xsession
SessionDir=/usr/share/xsessions
SessionLogFile=.local/share/sddm/xorg-session.log
UserAuthFile=.Xauthority
XauthPath=/usr/bin/xauth
XephyrPath=/usr/bin/Xephyr
```

### PR DESCRIPTION
**Pull request by outloudvi**
Resolve partially on #277.

> ...and try a few times before giving up...

### CODE REVIEW

**Comment by reubenvarghese1** [comment]
I can confirm that this seems to be fixing the issue. Typically, the best solution would be to find why the module is failing to unload but this fix seems to work just as fine . Most importantly, I do not notice difference even in spite of the multiple tries. This could be used as a temporary fix until something better is found.

**Comment by codepiyush** [comment]
This fix really works. Thanks

**Comment by reubenvarghese1** [comment]
@codepiyush From my understanding, a fix was already pushed to master. So if you pull the latest code, it should work right away

**Comment by codepiyush** [comment]
@reubenvarghese1 i am using the master version because i have amd igpu, but my issue was not resolved. I am a newbie so i may have done something wrong though.

**Comment by outloudvi** [comment]
https://github.com/Askannz/optimus-manager/commit/831abd8a46900722b7dc6cc513b791cb8b3de4f6 seems to be working for me. Closing this.
For first-time visitors here: the solution in this PR should be working, but is absolutely not the best. Use the master branch for a more reasonable solution.

**Pull request closed without merging**
