### PR TITLE
Add dynamic startup mode

### LINKED ISSUE #168: make startup mode depend on battery/AC
It would be nice to have the startup mode depend on the power status, e.g., a setting like
 - AC: nvidia
 - battery: intel

I could hack together a script for this locally but I'm willing to contribute a proper PR if there is interest in this feature. Maybe there could be simply a setting `power` that is defined as above.

### PR DESCRIPTION
**Pull request by aouerfelli**
Closes #168

### CODE REVIEW

**Comment by Askannz** [comment]
Thanks for that !

Wouldn't it make more sense to have this new dynamic option as a startup mode (alongside intel, nvidia, hybrid) ?

With your implementation, the user-defined startup mode is completely ignored when the dynamic option is set, which could be source of confusion. I think it would be better for the user to do something like this:

```
optimus-manager --set-startup ac_auto
```

**Comment by aouerfelli** [comment]
The reason I chose not to do that is because I didn't want to force the use
of a predetermined startup mode when not running on AC (some users might
still want to use intel over hybrid when not plugged in). However, since
this doesn't affect me, I wouldn't mind changing it to be a startup mode if
that's what you'd like. It works either way since users can still switch to
other modes manually when using an ac_auto startup mode.

**Comment by Askannz** [comment]
Here's how I see it:

* We add a new startup mode, `ac_auto`, that boots to nvidia when on AC or topre-determined mode when on battery

* This pre-determined mode is specified in the config file (section `[optimus]`, option `ac_auto_battery_mode` or something like that. By default this option is set to `intel`)

What do you think ?

**Comment by aouerfelli** [comment]
Sounds good. I'll comment on here again after I make those changes.

**Comment by aouerfelli** [comment]
I finished making the changes. Tested things on my end and it works fine. Let me know if you'd like me to change anything else.

**Comment by Askannz** [comment]
Turns out the AC detection doesn't work on my laptop, because for some reason the AC adapter is named `ADP1` instead of `AC`. So I changed `is_ac_power_connected()` a bit to iterate through all power source and pick the first one with a `Mains` type.

Other than that, looks good to me :slightly_smiling_face:

**Pull request merged**
