### PR TITLE
Merge "integrated" and amd modes. 

### PR DESCRIPTION
**Pull request by Hyper-KVM**
I think we should merge "integrated" and amd modes together so it's just one option "integrated" and using the function `get_available_igpu()` in pci.py to check which igpu is in the system. xsetup and xorg config files for additional configuration should be able to fit under one file, I can't see a reason to split them as having both an Intel, AMD, and nvidia GPU in one system just seems incredibly unlikely and this makes it more efficient.  Also in error_checking.py we can use `get_integrated_gpu()` in checks.py to return detected gpu mode and mask it as "integrated" while also checking the detected iGPU from the same `get_available_igpu()` function from pci.py.

### CODE REVIEW

**Comment by Hyper-KVM** [comment]
Added ability to use other xrandr providers because PRIME synchronization doesn't work on AMD (yet?). With Xorg AMD driver I can use TearFree option in nvidia mode and that totally solves the tearing and vsync issue as well, (144FPS in glxgears vs way over that lol) due to not having PRIME sync. Also decided to just use the existing make integrated device functions and I did test them, they do work just fine.

**Comment by bjsowa** [comment]
I tried to use this fork, but I got an error:

```
[9] INFO: # Xorg pre-start hook
[9] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[9] INFO: Requested mode is: integrated
[9] INFO: Checking for GDM display servers
[298] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[298] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[306] INFO: Loaded extra integrated Xorg options (0 lines)
[307] INFO: Loaded extra nvidia Xorg options (0 lines)
[307] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 46, in main
    configure_xorg(config, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/xorg.py", line 18, in configure_xorg
    available_igpu = get_available_igpu()
TypeError: get_available_igpu() missing 2 required positional arguments: 'match_pci_class' and 'match_vendor_id'
[308] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[308] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200825T221404', 'requested_mode': 'integrated'}
```

**Comment by Hyper-KVM** [comment]
> I tried to use this fork, but I got an error:
How did you install this fork?

**Comment by bjsowa** [comment]
> > I tried to use this fork, but I got an error:
> 
> How did you install this fork?

I cloned your fork (the `amd-hybrid` branch), Changed `source` in PKGBUILD to:
```
git+https://github.com/Hyper-KVM/optimus-manager.git#branch=amd-hybrid
```
and used `makepkg`.

**Comment by bjsowa** [comment]
By the way, what's the difference between your `amd-hybrid` branch and `amd_support` branch on this repo?

**Comment by Hyper-KVM** [comment]
> By the way, what's the difference between your `amd-hybrid` branch and `amd_support` branch on this repo?

I only have amd-hybrid, not amd_support branch, though I do have that amd_support branch with optimus-manager-qt.

**Comment by bjsowa** [comment]
I meant this branch:
https://github.com/Askannz/optimus-manager/tree/amd_support

It seems it already has the `integrated` mode which supports both intel and amd

**Comment by Askannz** [comment]
Finally reviewing this pull request. For future PRs, it'd be best to split independent changes into individual PRs, to facilitate the review work.

Comments on the changes:
* README typo/fixes and including AMD when mentioning iGPUs : OK
* Fixed "xrand" typo in logging: OK
* Auto-fallback on `modesetting` if the Xorg module `amdgpu` is unavailable + client warning about it: OK
* Allow to use amdgpu/intel as providers for Prime setup ([line](https://github.com/Askannz/optimus-manager/pull/268/files#diff-c3f83eaba4109c1cd47d8816c1135829R82)). I think you may have gotten that one wrong. The `driver` option in the `[amd]/[intel]` sections of the config file only affect the `integrated` mode. The Xorg driver for `hybrid` is always `modesetting`, so there is no need to adapt the xrandr command.
* Merging "intel" and "amd" section into "integrated": eeeeh, not a fan of that one. It currently works because Intel and AMD share the same options, but what if we have to implement a config option in the future that's only specific to one GPU vendor ? I get the idea of having one config section per GPU mode, but we also don't have one for "hybrid" so that logic kinda breaks down. Besides, it breaks existing config files, which is something I'd really like to avoid.
* Merging xsetup scripts for intel and amd: OK, makes sense.
* Merging extra xorg config files for intel and amd in favor of a single "integrated" one: OK, but I have renamed the files to `xorg-integrated-gpu.conf` and `xorg-nvidia-gpu.conf` to avoid confusion.

I cherry-picked the accepted changes and authored @Hyper-KVM on them.

**Pull request closed without merging**
