### PR TITLE
Add BashError class and rework exec_bash's references

### PR DESCRIPTION
**Pull request by kuroni**
This leads to all kind of interesting maneuvers I suppose :D

Also fix a minor issue in README.md

### CODE REVIEW

**Comment by Askannz** [comment]
Someone's been reading my TODOs :D

And yeah, good catch on the README, can't believe I fucked it up again :man_facepalming:

**Comment by kuroni** [comment]
Anyway, although not relating to the PR, do you plan on documenting the modules and functions for future ease?

**Comment by Askannz** [comment]
I'll probably sprinkle a few comments at some point, yeah. Although most of the code should be self-explanatory already. Besides, it's not like the modules and functions are intended to be used outside this program :man_shrugging:

**Comment by kuroni** [comment]
To both of your question, I'm almost certain that checking the stderr of `modprobe` or `rmmod` is the equivalent of rechecking whether the modules are loaded/unloaded successfully. The only problem here is, as you mentioned, executing `rmmod` on an unloaded module yields error, and that is what we want to avoid.

Luckily, upon searching, I found out that `modprobe -r` would remove the modules just like `rmmod`, but will not sport out errors in case of the module being unloaded is not loaded in the first place. I just pushed another commit fixing on this.

**Comment by Askannz** [comment]
Ah, I read the PR too fast, I though you were doing a check on the return code of bash, but you're actually checking if stderr is empty (doesn't change my previous remarks though).

I think that goes against the UNIX philosophy, what if the command succeeds but decides to print a warning there ? (warnings should go to stderr according to StackOverflow : https://stackoverflow.com/questions/1430956/should-i-output-warnings-to-stderr-or-stdout).

**Comment by Askannz** [comment]
We could check the return code instead, but some functions already expect that return code directly...so, we have two options :

1. Have those functions catch a `BashError` instead of checking `returncode != 0`
2. Leave `exec_bash()` as it was before but have a return code check everywhere it's used

On a side note, it seems that `modprobe -r` also has a zero return code when the module is not loaded. So your idea of replacing rmmod + lsmod by modprobe -r is still valid.

**Comment by kuroni** [comment]
Checking the return code, however, is also not always 100% correct. `cat /proc/acpi/bbswitch | cut -d' ' -f 2` will yield a 0 return code even when stderr reports `cat: /proc/acpi/bbswitch: No such file or directory`.

I will research on this topic more thoroughly, seems like the problem is way more difficult than we think it is ;)

**Comment by Askannz** [comment]
Tested and merged :+1:

**Pull request merged**
