### PR TITLE
Remove Bumblebee Vulkan drawback (no longer true)

### PR DESCRIPTION
**Pull request by jonpas**
README states one major drawback on using Bumblebee is no support for Vulkan however that is no longer true since [primus_vk](https://github.com/felixdoerre/primus_vk) is a thing.

### CODE REVIEW

**Comment by Askannz** [comment]
Is primus_vk in a usable state yet though ? I have not seen a lot of people report about it, and it looks quite complicated to set up (probably why no distro has official support for it yet). I think most users would not bother with it, so the point about bumblebee lacking Vulkan support still stands.

**Comment by Askannz** [comment]
I have reformatted the paragraph about bumblebee to be more readable. If you want, you can add a line in the Vulkan subsection to mention the existence of primus_vk, but please also state that it is still a WIP solution and requires some work to set up.

**Comment by Askannz** [comment]
primus_vk does look promising though, will definitely give it some testing  :smiley:

**Comment by jonpas** [comment]
I am using it for solid 2 months now without issues apart from initial setup. Arch and Debian have packages for it as well.

**Comment by jonpas** [comment]
This could be changed now, primus-vk is much more stable now.

**Comment by Askannz** [comment]
A mention of primus_vk was added in the wiki.

**Pull request closed without merging**
